---
resource:
  name: configuration_deploy
  rest_endpoint: /lan-fabric/rest/control/fabrics/%s/inventory/switchesByFabric
  doc_category: Fabric
  generate_tf_resource: true
  skip_codec: true
  attributes:
    - &id
      model_name: id
      tf_name: id
      description: The Terraform Unique Identifier for the Inventory Devices resource
      type: String
      id: true
      use_state: true
      computed: true
      ndfc_type: string
    - &fabric_name
      model_name: fabricName
      tf_name: fabric_name
      reference: true
      description: The name of the fabric
      type: String
      example: CML
      mandatory: true
      tf_requires_replace: true
      ndfc_type: string
    - &serial_numbers
      model_name: serialNumbers
      tf_name: serial_numbers
      description: Value 'ALL' if all switches in the fabric are to be deployed, or a list of serial numbers of the switches to be deployed
      type: List:String
      example: "[ \"FGE20360RRZ\", \"FGE20360RRY\" ]"
      ndfc_type: set
    - &config_save
      model_name: configSave
      tf_name: config_save
      type: Bool
      description: Save the configuration
      default_value: false
      ndfc_type: bool
      payload_hide: true
      example: true
    - &deploy
      model_name: deploy
      tf_name: deploy
      type: Bool
      description: >-
            This is a boolean value.
            If set to false, no deployment is done, it basically no operation in NDFC.
            If set to true, the switches are deployed and the flag will be toggled back to false after the deployment is completed,
            when terraform refresh is performed. Terraform plan will always show in-place update for this field when set to true.
      ndfc_type: bool
      payload_hide: true
      mandatory: true