---
ndfc: 
  url: "https://10.78.210.161"
  user: admin
  pwd: "admin!@#"
  insecure: true
  fabric: CML
  switches:
    - "9FE076D8EJL"
    - "9TQYTJSZ1VJ"
    - "9QBCTIN0FMY"
  vrf_prefix: "vrf_acc_test_"
  net_prefix: "net_acc_test_"
