---
ndfc: 
  url: "https://172.25.74.175"
  user: admin
  pwd: "admin!@#"
  insecure: true
  fabric: CML
  switches:
    - "9SSXXLEGO3J"
    - "9XAE2OCJD8B"
    - "9B18T9Z8VLS"
  vrf_prefix: "vrf_a_test_"
  net_prefix: "net_a_test_"
  vpc_pair: 
    - "9KQAM6STEBY"
    - "9B18T9Z8VLS"
  integration_test: 
    fabric: at_test_vxlan
    switches:
      - ""
      - ""
      - ""
