// Copyright (c) 2025 Cisco Systems, Inc. and its affiliates
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated;  DO NOT EDIT.

package resource_fabric_common

import (
	. "terraform-provider-ndfc/internal/provider/types"
)

type NDFCFabricCommonModel struct {
	FabricName                              string       `json:"FABRIC_NAME,omitempty"`
	AaaRemoteIpEnabled                      string       `json:"AAA_REMOTE_IP_ENABLED,omitempty"`
	AaaServerConf                           string       `json:"AAA_SERVER_CONF,omitempty"`
	AsmGroupRanges                          string       `json:"ASM_GROUP_RANGES,omitempty"`
	BootstrapConf                           string       `json:"BOOTSTRAP_CONF,omitempty"`
	BootstrapEnable                         string       `json:"BOOTSTRAP_ENABLE,omitempty"`
	BootstrapMultisubnet                    string       `json:"BOOTSTRAP_MULTISUBNET,omitempty"`
	CdpEnable                               string       `json:"CDP_ENABLE,omitempty"`
	DhcpEnable                              string       `json:"DHCP_ENABLE,omitempty"`
	DhcpEnd                                 string       `json:"DHCP_END,omitempty"`
	DhcpIpv6Enable                          string       `json:"DHCP_IPV6_ENABLE,omitempty"`
	DhcpStart                               string       `json:"DHCP_START,omitempty"`
	DnsServerIpList                         string       `json:"DNS_SERVER_IP_LIST,omitempty"`
	DnsServerVrf                            string       `json:"DNS_SERVER_VRF,omitempty"`
	EnableAaa                               string       `json:"ENABLE_AAA,omitempty"`
	EsrOption                               string       `json:"ESR_OPTION,omitempty"`
	EnableNbmPassive                        string       `json:"ENABLE_NBM_PASSIVE,omitempty"`
	ExtraConfIntraLinks                     string       `json:"EXTRA_CONF_INTRA_LINKS,omitempty"`
	ExtraConfLeaf                           string       `json:"EXTRA_CONF_LEAF,omitempty"`
	ExtraConfSpine                          string       `json:"EXTRA_CONF_SPINE,omitempty"`
	FabricInterfaceType                     string       `json:"FABRIC_INTERFACE_TYPE,omitempty"`
	FabricMtu                               *Int64Custom `json:"FABRIC_MTU,omitempty"`
	FeaturePtp                              string       `json:"FEATURE_PTP,omitempty"`
	IsisAuthEnable                          string       `json:"ISIS_AUTH_ENABLE,omitempty"`
	IsisAuthKey                             string       `json:"ISIS_AUTH_KEY,omitempty"`
	IsisAuthKeychainKeyId                   *Int64Custom `json:"ISIS_AUTH_KEYCHAIN_KEY_ID,omitempty"`
	IsisAuthKeychainName                    string       `json:"ISIS_AUTH_KEYCHAIN_NAME,omitempty"`
	IsisLevel                               string       `json:"ISIS_LEVEL,omitempty"`
	IsisP2pEnable                           string       `json:"ISIS_P2P_ENABLE,omitempty"`
	L2HostIntfMtu                           *Int64Custom `json:"L2_HOST_INTF_MTU,omitempty"`
	LinkStateRouting                        string       `json:"LINK_STATE_ROUTING,omitempty"`
	LinkStateRoutingTag                     string       `json:"LINK_STATE_ROUTING_TAG,omitempty"`
	Loopback0IpRange                        string       `json:"LOOPBACK0_IP_RANGE,omitempty"`
	MgmtGw                                  string       `json:"MGMT_GW,omitempty"`
	MgmtPrefix                              *Int64Custom `json:"MGMT_PREFIX,omitempty"`
	NtpServerIpList                         string       `json:"NTP_SERVER_IP_LIST,omitempty"`
	NtpServerVrf                            string       `json:"NTP_SERVER_VRF,omitempty"`
	NxapiVrf                                string       `json:"NXAPI_VRF,omitempty"`
	OspfAreaId                              string       `json:"OSPF_AREA_ID,omitempty"`
	OspfAuthEnable                          string       `json:"OSPF_AUTH_ENABLE,omitempty"`
	OspfAuthKey                             string       `json:"OSPF_AUTH_KEY,omitempty"`
	OspfAuthKeyId                           *Int64Custom `json:"OSPF_AUTH_KEY_ID,omitempty"`
	PimHelloAuthEnable                      string       `json:"PIM_HELLO_AUTH_ENABLE,omitempty"`
	PimHelloAuthKey                         string       `json:"PIM_HELLO_AUTH_KEY,omitempty"`
	PmEnable                                string       `json:"PM_ENABLE,omitempty"`
	PowerRedundancyMode                     string       `json:"POWER_REDUNDANCY_MODE,omitempty"`
	PtpDomainId                             *Int64Custom `json:"PTP_DOMAIN_ID,omitempty"`
	PtpLbId                                 *Int64Custom `json:"PTP_LB_ID,omitempty"`
	PtpProfile                              string       `json:"PTP_PROFILE,omitempty"`
	RoutingLbId                             *Int64Custom `json:"ROUTING_LB_ID,omitempty"`
	RpIpRange                               string       `json:"RP_IP_RANGE,omitempty"`
	RpLbId                                  *Int64Custom `json:"RP_LB_ID,omitempty"`
	SnmpServerHostTrap                      string       `json:"SNMP_SERVER_HOST_TRAP,omitempty"`
	StaticUnderlayIpAlloc                   string       `json:"STATIC_UNDERLAY_IP_ALLOC,omitempty"`
	SubnetRange                             string       `json:"SUBNET_RANGE,omitempty"`
	SubnetTargetMask                        *Int64Custom `json:"SUBNET_TARGET_MASK,omitempty"`
	SyslogServerIpList                      string       `json:"SYSLOG_SERVER_IP_LIST,omitempty"`
	SyslogServerVrf                         string       `json:"SYSLOG_SERVER_VRF,omitempty"`
	SyslogSev                               string       `json:"SYSLOG_SEV,omitempty"`
	BgpAs                                   string       `json:"BGP_AS,omitempty"`
	BootstrapConfXe                         string       `json:"BOOTSTRAP_CONF_XE,omitempty"`
	DomainName                              string       `json:"DOMAIN_NAME,omitempty"`
	EnableNetflow                           string       `json:"ENABLE_NETFLOW,omitempty"`
	EnableNxapi                             string       `json:"ENABLE_NXAPI,omitempty"`
	EnableNxapiHttp                         string       `json:"ENABLE_NXAPI_HTTP,omitempty"`
	EnableRtIntfStats                       string       `json:"ENABLE_RT_INTF_STATS,omitempty"`
	FabricFreeform                          string       `json:"FABRIC_FREEFORM,omitempty"`
	InbandEnable                            string       `json:"INBAND_ENABLE,omitempty"`
	InbandMgmt                              string       `json:"INBAND_MGMT,omitempty"`
	IntfStatLoadInterval                    *Int64Custom `json:"INTF_STAT_LOAD_INTERVAL,omitempty"`
	IsReadOnly                              string       `json:"IS_READ_ONLY,omitempty"`
	MgmtV6prefix                            *Int64Custom `json:"MGMT_V6PREFIX,omitempty"`
	MplsHandoff                             string       `json:"MPLS_HANDOFF,omitempty"`
	MplsLbId                                *Int64Custom `json:"MPLS_LB_ID,omitempty"`
	MplsLoopbackIpRange                     string       `json:"MPLS_LOOPBACK_IP_RANGE,omitempty"`
	NetflowExporterList                     string       `json:"NETFLOW_EXPORTER_LIST,omitempty"`
	NetflowMonitorList                      string       `json:"NETFLOW_MONITOR_LIST,omitempty"`
	NetflowRecordList                       string       `json:"NETFLOW_RECORD_LIST,omitempty"`
	NetflowSamplerList                      string       `json:"NETFLOW_SAMPLER_LIST,omitempty"`
	NxapiHttpsPort                          *Int64Custom `json:"NXAPI_HTTPS_PORT,omitempty"`
	NxapiHttpPort                           *Int64Custom `json:"NXAPI_HTTP_PORT,omitempty"`
	PnpEnable                               string       `json:"PNP_ENABLE,omitempty"`
	SubinterfaceRange                       string       `json:"SUBINTERFACE_RANGE,omitempty"`
	EnableRealTimeBackup                    string       `json:"enableRealTimeBackup,omitempty"`
	EnableScheduledBackup                   string       `json:"enableScheduledBackup,omitempty"`
	ScheduledTime                           string       `json:"scheduledTime,omitempty"`
	AdvertisePipBgp                         string       `json:"ADVERTISE_PIP_BGP,omitempty"`
	AdvertisePipOnBorder                    string       `json:"ADVERTISE_PIP_ON_BORDER,omitempty"`
	AnycastBgwAdvertisePip                  string       `json:"ANYCAST_BGW_ADVERTISE_PIP,omitempty"`
	AnycastGwMac                            string       `json:"ANYCAST_GW_MAC,omitempty"`
	AnycastLbId                             *Int64Custom `json:"ANYCAST_LB_ID,omitempty"`
	AnycastRpIpRange                        string       `json:"ANYCAST_RP_IP_RANGE,omitempty"`
	AutoSymmetricDefaultVrf                 string       `json:"AUTO_SYMMETRIC_DEFAULT_VRF,omitempty"`
	AutoSymmetricVrfLite                    string       `json:"AUTO_SYMMETRIC_VRF_LITE,omitempty"`
	AutoUniqueVrfLiteIpPrefix               string       `json:"AUTO_UNIQUE_VRF_LITE_IP_PREFIX,omitempty"`
	AutoVrfliteIfcDefaultVrf                string       `json:"AUTO_VRFLITE_IFC_DEFAULT_VRF,omitempty"`
	Banner                                  string       `json:"BANNER,omitempty"`
	BfdAuthEnable                           string       `json:"BFD_AUTH_ENABLE,omitempty"`
	BfdAuthKey                              string       `json:"BFD_AUTH_KEY,omitempty"`
	BfdAuthKeyId                            *Int64Custom `json:"BFD_AUTH_KEY_ID,omitempty"`
	BfdEnable                               string       `json:"BFD_ENABLE,omitempty"`
	BfdIbgpEnable                           string       `json:"BFD_IBGP_ENABLE,omitempty"`
	BfdIsisEnable                           string       `json:"BFD_ISIS_ENABLE,omitempty"`
	BfdOspfEnable                           string       `json:"BFD_OSPF_ENABLE,omitempty"`
	BfdPimEnable                            string       `json:"BFD_PIM_ENABLE,omitempty"`
	BgpAuthEnable                           string       `json:"BGP_AUTH_ENABLE,omitempty"`
	BgpAuthKey                              string       `json:"BGP_AUTH_KEY,omitempty"`
	BgpAuthKeyType                          *Int64Custom `json:"BGP_AUTH_KEY_TYPE,omitempty"`
	BgpLbId                                 *Int64Custom `json:"BGP_LB_ID,omitempty"`
	BrownfieldNetworkNameFormat             string       `json:"BROWNFIELD_NETWORK_NAME_FORMAT,omitempty"`
	BrownfieldSkipOverlayNetworkAttachments string       `json:"BROWNFIELD_SKIP_OVERLAY_NETWORK_ATTACHMENTS,omitempty"`
	CoppPolicy                              string       `json:"COPP_POLICY,omitempty"`
	DciSubnetRange                          string       `json:"DCI_SUBNET_RANGE,omitempty"`
	DciSubnetTargetMask                     *Int64Custom `json:"DCI_SUBNET_TARGET_MASK,omitempty"`
	DefaultQueuingPolicyCloudscale          string       `json:"DEAFULT_QUEUING_POLICY_CLOUDSCALE,omitempty"`
	DefaultQueuingPolicyOther               string       `json:"DEAFULT_QUEUING_POLICY_OTHER,omitempty"`
	DefaultQueuingPolicyRSeries             string       `json:"DEAFULT_QUEUING_POLICY_R_SERIES,omitempty"`
	DefaultVrfRedisBgpRmap                  string       `json:"DEFAULT_VRF_REDIS_BGP_RMAP,omitempty"`
	EnableDefaultQueuingPolicy              string       `json:"ENABLE_DEFAULT_QUEUING_POLICY,omitempty"`
	EnableFabricVpcDomainId                 string       `json:"ENABLE_FABRIC_VPC_DOMAIN_ID,omitempty"`
	EnableMacsec                            string       `json:"ENABLE_MACSEC,omitempty"`
	EnableNgoam                             string       `json:"ENABLE_NGOAM,omitempty"`
	EnablePbr                               string       `json:"ENABLE_PBR,omitempty"`
	EnablePvlan                             string       `json:"ENABLE_PVLAN,omitempty"`
	EnableTenantDhcp                        string       `json:"ENABLE_TENANT_DHCP,omitempty"`
	EnableTrm                               string       `json:"ENABLE_TRM,omitempty"`
	EnableVpcPeerLinkNativeVlan             string       `json:"ENABLE_VPC_PEER_LINK_NATIVE_VLAN,omitempty"`
	ExtraConfTor                            string       `json:"EXTRA_CONF_TOR,omitempty"`
	FabricVpcDomainId                       *Int64Custom `json:"FABRIC_VPC_DOMAIN_ID,omitempty"`
	FabricVpcQos                            string       `json:"FABRIC_VPC_QOS,omitempty"`
	FabricVpcQosPolicyName                  string       `json:"FABRIC_VPC_QOS_POLICY_NAME,omitempty"`
	GrfieldDebugFlag                        string       `json:"GRFIELD_DEBUG_FLAG,omitempty"`
	HdTime                                  *Int64Custom `json:"HD_TIME,omitempty"`
	HostIntfAdminState                      string       `json:"HOST_INTF_ADMIN_STATE,omitempty"`
	IbgpPeerTemplate                        string       `json:"IBGP_PEER_TEMPLATE,omitempty"`
	IbgpPeerTemplateLeaf                    string       `json:"IBGP_PEER_TEMPLATE_LEAF,omitempty"`
	InbandDhcpServers                       string       `json:"INBAND_DHCP_SERVERS,omitempty"`
	IsisOverloadElapseTime                  *Int64Custom `json:"ISIS_OVERLOAD_ELAPSE_TIME,omitempty"`
	IsisOverloadEnable                      string       `json:"ISIS_OVERLOAD_ENABLE,omitempty"`
	L2SegmentIdRange                        string       `json:"L2_SEGMENT_ID_RANGE,omitempty"`
	L3vniMcastGroup                         string       `json:"L3VNI_MCAST_GROUP,omitempty"`
	L3PartitionIdRange                      string       `json:"L3_PARTITION_ID_RANGE,omitempty"`
	Loopback0Ipv6Range                      string       `json:"LOOPBACK0_IPV6_RANGE,omitempty"`
	Loopback1Ipv6Range                      string       `json:"LOOPBACK1_IPV6_RANGE,omitempty"`
	Loopback1IpRange                        string       `json:"LOOPBACK1_IP_RANGE,omitempty"`
	MacsecAlgorithm                         string       `json:"MACSEC_ALGORITHM,omitempty"`
	MacsecCipherSuite                       string       `json:"MACSEC_CIPHER_SUITE,omitempty"`
	MacsecFallbackAlgorithm                 string       `json:"MACSEC_FALLBACK_ALGORITHM,omitempty"`
	MacsecFallbackKeyString                 string       `json:"MACSEC_FALLBACK_KEY_STRING,omitempty"`
	MacsecKeyString                         string       `json:"MACSEC_KEY_STRING,omitempty"`
	MacsecReportTimer                       *Int64Custom `json:"MACSEC_REPORT_TIMER,omitempty"`
	MstInstanceRange                        string       `json:"MST_INSTANCE_RANGE,omitempty"`
	MulticastGroupSubnet                    string       `json:"MULTICAST_GROUP_SUBNET,omitempty"`
	NetworkVlanRange                        string       `json:"NETWORK_VLAN_RANGE,omitempty"`
	NveLbId                                 *Int64Custom `json:"NVE_LB_ID,omitempty"`
	ObjectTrackingNumberRange               string       `json:"OBJECT_TRACKING_NUMBER_RANGE,omitempty"`
	OverlayMode                             string       `json:"OVERLAY_MODE,omitempty"`
	PerVrfLoopbackAutoProvision             string       `json:"PER_VRF_LOOPBACK_AUTO_PROVISION,omitempty"`
	PerVrfLoopbackIpRange                   string       `json:"PER_VRF_LOOPBACK_IP_RANGE,omitempty"`
	PhantomRpLbId1                          *Int64Custom `json:"PHANTOM_RP_LB_ID1,omitempty"`
	PhantomRpLbId2                          *Int64Custom `json:"PHANTOM_RP_LB_ID2,omitempty"`
	PhantomRpLbId3                          *Int64Custom `json:"PHANTOM_RP_LB_ID3,omitempty"`
	PhantomRpLbId4                          *Int64Custom `json:"PHANTOM_RP_LB_ID4,omitempty"`
	ReplicationMode                         string       `json:"REPLICATION_MODE,omitempty"`
	RouterIdRange                           string       `json:"ROUTER_ID_RANGE,omitempty"`
	RouteMapSequenceNumberRange             string       `json:"ROUTE_MAP_SEQUENCE_NUMBER_RANGE,omitempty"`
	RpCount                                 *Int64Custom `json:"RP_COUNT,omitempty"`
	RpMode                                  string       `json:"RP_MODE,omitempty"`
	RrCount                                 *Int64Custom `json:"RR_COUNT,omitempty"`
	SeedSwitchCoreInterfaces                string       `json:"SEED_SWITCH_CORE_INTERFACES,omitempty"`
	ServiceNetworkVlanRange                 string       `json:"SERVICE_NETWORK_VLAN_RANGE,omitempty"`
	SiteId                                  string       `json:"SITE_ID,omitempty"`
	SlaIdRange                              string       `json:"SLA_ID_RANGE,omitempty"`
	SpineSwitchCoreInterfaces               string       `json:"SPINE_SWITCH_CORE_INTERFACES,omitempty"`
	StpBridgePriority                       *Int64Custom `json:"STP_BRIDGE_PRIORITY,omitempty"`
	StpRootOption                           string       `json:"STP_ROOT_OPTION,omitempty"`
	StpVlanRange                            string       `json:"STP_VLAN_RANGE,omitempty"`
	StrictCcMode                            string       `json:"STRICT_CC_MODE,omitempty"`
	TcamAllocation                          string       `json:"TCAM_ALLOCATION,omitempty"`
	UnderlayIsV6                            string       `json:"UNDERLAY_IS_V6,omitempty"`
	UnnumBootstrapLbId                      *Int64Custom `json:"UNNUM_BOOTSTRAP_LB_ID,omitempty"`
	UnnumDhcpEnd                            string       `json:"UNNUM_DHCP_END,omitempty"`
	UnnumDhcpStart                          string       `json:"UNNUM_DHCP_START,omitempty"`
	UseLinkLocal                            string       `json:"USE_LINK_LOCAL,omitempty"`
	V6SubnetRange                           string       `json:"V6_SUBNET_RANGE,omitempty"`
	V6SubnetTargetMask                      *Int64Custom `json:"V6_SUBNET_TARGET_MASK,omitempty"`
	VpcAutoRecoveryTime                     *Int64Custom `json:"VPC_AUTO_RECOVERY_TIME,omitempty"`
	VpcDelayRestore                         *Int64Custom `json:"VPC_DELAY_RESTORE,omitempty"`
	VpcDomainIdRange                        string       `json:"VPC_DOMAIN_ID_RANGE,omitempty"`
	VpcEnableIpv6NdSync                     string       `json:"VPC_ENABLE_IPv6_ND_SYNC,omitempty"`
	VpcPeerKeepAliveOption                  string       `json:"VPC_PEER_KEEP_ALIVE_OPTION,omitempty"`
	VpcPeerLinkPo                           *Int64Custom `json:"VPC_PEER_LINK_PO,omitempty"`
	VpcPeerLinkVlan                         *Int64Custom `json:"VPC_PEER_LINK_VLAN,omitempty"`
	VrfLiteAutoconfig                       string       `json:"VRF_LITE_AUTOCONFIG,omitempty"`
	VrfVlanRange                            string       `json:"VRF_VLAN_RANGE,omitempty"`
	DefaultNetwork                          string       `json:"default_network,omitempty"`
	DefaultPvlanSecNetwork                  string       `json:"default_pvlan_sec_network,omitempty"`
	DefaultVrf                              string       `json:"default_vrf,omitempty"`
	NetworkExtensionTemplate                string       `json:"network_extension_template,omitempty"`
	VrfExtensionTemplate                    string       `json:"vrf_extension_template,omitempty"`
	BgpRpAsn                                string       `json:"BGP_RP_ASN,omitempty"`
	BorderGwyConnections                    string       `json:"BORDER_GWY_CONNECTIONS,omitempty"`
	CloudsecAlgorithm                       string       `json:"CLOUDSEC_ALGORITHM,omitempty"`
	CloudsecAutoconfig                      string       `json:"CLOUDSEC_AUTOCONFIG,omitempty"`
	CloudsecEnforcement                     string       `json:"CLOUDSEC_ENFORCEMENT,omitempty"`
	CloudsecKeyString                       string       `json:"CLOUDSEC_KEY_STRING,omitempty"`
	CloudsecReportTimer                     *Int64Custom `json:"CLOUDSEC_REPORT_TIMER,omitempty"`
	DelayRestore                            *Int64Custom `json:"DELAY_RESTORE,omitempty"`
	EnableBgpBfd                            string       `json:"ENABLE_BGP_BFD,omitempty"`
	EnableBgpLogNeighborChange              string       `json:"ENABLE_BGP_LOG_NEIGHBOR_CHANGE,omitempty"`
	EnableBgpSendComm                       string       `json:"ENABLE_BGP_SEND_COMM,omitempty"`
	EnableRsRedistDirect                    string       `json:"ENABLE_RS_REDIST_DIRECT,omitempty"`
	Loopback100IpRange                      string       `json:"LOOPBACK100_IP_RANGE,omitempty"`
	MsIfcBgpAuthKeyType                     *Int64Custom `json:"MS_IFC_BGP_AUTH_KEY_TYPE,omitempty"`
	MsIfcBgpPassword                        string       `json:"MS_IFC_BGP_PASSWORD,omitempty"`
	MsIfcBgpPasswordEnable                  string       `json:"MS_IFC_BGP_PASSWORD_ENABLE,omitempty"`
	MsLoopbackId                            *Int64Custom `json:"MS_LOOPBACK_ID,omitempty"`
	MsUnderlayAutoconfig                    string       `json:"MS_UNDERLAY_AUTOCONFIG,omitempty"`
	RpServerIp                              string       `json:"RP_SERVER_IP,omitempty"`
	RsRoutingTag                            *Int64Custom `json:"RS_ROUTING_TAG,omitempty"`
	TorAutoDeploy                           string       `json:"TOR_AUTO_DEPLOY,omitempty"`
	Deploy                                  bool         `json:"-"`
	DeploymentStatus                        string       `json:"-"`
	Ipv6MulticastGroupSubnet                string       `json:"IPv6_MULTICAST_GROUP_SUBNET,omitempty"`
	EnableTrmv6                             string       `json:"ENABLE_TRMv6,omitempty"`
	L3vniIpv6McastGroup                     string       `json:"L3VNI_IPv6_MCAST_GROUP,omitempty"`
	MvpnVriIdRange                          string       `json:"MVPN_VRI_ID_RANGE,omitempty"`
	EnableVriIdRealloc                      string       `json:"ENABLE_VRI_ID_REALLOC,omitempty"`
	EnableAggAccIdRange                     string       `json:"ENABLE_AGG_ACC_ID_RANGE,omitempty"`
	AggAccVpcPoIdRange                      string       `json:"AGG_ACC_VPC_PO_ID_RANGE,omitempty"`
	IsisAreaNum                             string       `json:"ISIS_AREA_NUM,omitempty"`
	EnableSgt                               string       `json:"ENABLE_SGT,omitempty"`
	SgtNamePrefix                           string       `json:"SGT_NAME_PREFIX,omitempty"`
	SgtIdRange                              string       `json:"SGT_ID_RANGE,omitempty"`
	SgtPreprovision                         string       `json:"SGT_PREPROVISION,omitempty"`
	EnableDciMacsec                         string       `json:"ENABLE_DCI_MACSEC,omitempty"`
	EnableQkd                               string       `json:"ENABLE_QKD,omitempty"`
	AllowL3vniNoVlan                        string       `json:"ALLOW_L3VNI_NO_VLAN,omitempty"`
	EnableL3vniNoVlan                       string       `json:"ENABLE_L3VNI_NO_VLAN,omitempty"`
	MplsIsisAreaNum                         string       `json:"MPLS_ISIS_AREA_NUM,omitempty"`
	EnableAiMlQosPolicy                     string       `json:"ENABLE_AI_ML_QOS_POLICY,omitempty"`
	AiMlQosPolicy                           string       `json:"AI_ML_QOS_POLICY,omitempty"`
	PfcWatchInt                             *Int64Custom `json:"PFC_WATCH_INT,omitempty"`
	Ipv6AnycastRpIpRange                    string       `json:"IPv6_ANYCAST_RP_IP_RANGE,omitempty"`
	KmeServerIp                             string       `json:"KME_SERVER_IP,omitempty"`
	KmeServerPort                           *Int64Custom `json:"KME_SERVER_PORT,omitempty"`
	TrustpointLabel                         string       `json:"TRUSTPOINT_LABEL,omitempty"`
	IgnoreCert                              string       `json:"IGNORE_CERT,omitempty"`
	DeploymentFreeze                        string       `json:"DEPLOYMENT_FREEZE,omitempty"`
	QkdProfileName                          string       `json:"QKD_PROFILE_NAME,omitempty"`
	PerVrfLoopbackAutoProvisionV6           string       `json:"PER_VRF_LOOPBACK_AUTO_PROVISION_V6,omitempty"`
	PerVrfLoopbackIpRangeV6                 string       `json:"PER_VRF_LOOPBACK_IP_RANGE_V6,omitempty"`
	PtpVlanId                               *Int64Custom `json:"PTP_VLAN_ID,omitempty"`
	AllowNxc                                string       `json:"ALLOW_NXC,omitempty"`
	OverwriteGlobalNxc                      string       `json:"OVERWRITE_GLOBAL_NXC,omitempty"`
	NxcDestVrf                              string       `json:"NXC_DEST_VRF,omitempty"`
	NxcSrcIntf                              string       `json:"NXC_SRC_INTF,omitempty"`
	NxcProxyServer                          string       `json:"NXC_PROXY_SERVER,omitempty"`
	NxcProxyPort                            *Int64Custom `json:"NXC_PROXY_PORT,omitempty"`
	VpcDelayRestoreTime                     *Int64Custom `json:"VPC_DELAY_RESTORE_TIME,omitempty"`
	FabricType                              string       `json:"FABRIC_TYPE,omitempty"`
	ExtFabricType                           string       `json:"EXT_FABRIC_TYPE,omitempty"`
	EnableAgent                             string       `json:"ENABLE_AGENT,omitempty"`
	AgentIntf                               string       `json:"AGENT_INTF,omitempty"`
	SspineAddDelDebugFlag                   string       `json:"SSPINE_ADD_DEL_DEBUG_FLAG,omitempty"`
	BrfieldDebugFlag                        string       `json:"BRFIELD_DEBUG_FLAG,omitempty"`
	ActiveMigration                         string       `json:"ACTIVE_MIGRATION,omitempty"`
	Ff                                      string       `json:"FF,omitempty"`
	BgpAsPrev                               string       `json:"BGP_AS_PREV,omitempty"`
	UnderlayIsV6Prev                        string       `json:"UNDERLAY_IS_V6_PREV,omitempty"`
	PmEnablePrev                            string       `json:"PM_ENABLE_PREV,omitempty"`
	EnableFabricVpcDomainIdPrev             string       `json:"ENABLE_FABRIC_VPC_DOMAIN_ID_PREV,omitempty"`
	OverlayModePrev                         string       `json:"OVERLAY_MODE_PREV,omitempty"`
	AllowL3vniNoVlanPrev                    string       `json:"ALLOW_L3VNI_NO_VLAN_PREV,omitempty"`
	EnablePvlanPrev                         string       `json:"ENABLE_PVLAN_PREV,omitempty"`
	AutoUniqueVrfLiteIpPrefixPrev           string       `json:"AUTO_UNIQUE_VRF_LITE_IP_PREFIX_PREV,omitempty"`
	PerVrfLoopbackAutoProvisionPrev         string       `json:"PER_VRF_LOOPBACK_AUTO_PROVISION_PREV,omitempty"`
	PerVrfLoopbackAutoProvisionV6Prev       string       `json:"PER_VRF_LOOPBACK_AUTO_PROVISION_V6_PREV,omitempty"`
	MsoSiteId                               string       `json:"MSO_SITE_ID,omitempty"`
	MsoControlerId                          string       `json:"MSO_CONTROLER_ID,omitempty"`
	MsoSiteGroupName                        string       `json:"MSO_SITE_GROUP_NAME,omitempty"`
	PremsoParentFabric                      string       `json:"PREMSO_PARENT_FABRIC,omitempty"`
	MsoConnectivityDeployed                 string       `json:"MSO_CONNECTIVITY_DEPLOYED,omitempty"`
	AnycastRpIpRangeInternal                string       `json:"ANYCAST_RP_IP_RANGE_INTERNAL,omitempty"`
	Ipv6AnycastRpIpRangeInternal            string       `json:"IPv6_ANYCAST_RP_IP_RANGE_INTERNAL,omitempty"`
	DhcpStartInternal                       string       `json:"DHCP_START_INTERNAL,omitempty"`
	DhcpEndInternal                         string       `json:"DHCP_END_INTERNAL,omitempty"`
	MgmtGwInternal                          string       `json:"MGMT_GW_INTERNAL,omitempty"`
	MgmtPrefixInternal                      *Int64Custom `json:"MGMT_PREFIX_INTERNAL,omitempty"`
	BootstrapMultisubnetInternal            string       `json:"BOOTSTRAP_MULTISUBNET_INTERNAL,omitempty"`
	MgmtV6prefixInternal                    *Int64Custom `json:"MGMT_V6PREFIX_INTERNAL,omitempty"`
	DhcpIpv6EnableInternal                  string       `json:"DHCP_IPV6_ENABLE_INTERNAL,omitempty"`
	UnnumDhcpStartInternal                  string       `json:"UNNUM_DHCP_START_INTERNAL,omitempty"`
	UnnumDhcpEndInternal                    string       `json:"UNNUM_DHCP_END_INTERNAL,omitempty"`
	EnableEvpn                              string       `json:"ENABLE_EVPN,omitempty"`
	FeaturePtpInternal                      string       `json:"FEATURE_PTP_INTERNAL,omitempty"`
	SspineCount                             *Int64Custom `json:"SSPINE_COUNT,omitempty"`
	SpineCount                              *Int64Custom `json:"SPINE_COUNT,omitempty"`
	AbstractFeatureLeaf                     string       `json:"abstract_feature_leaf,omitempty"`
	AbstractFeatureSpine                    string       `json:"abstract_feature_spine,omitempty"`
	AbstractDhcp                            string       `json:"abstract_dhcp,omitempty"`
	AbstractMulticast                       string       `json:"abstract_multicast,omitempty"`
	AbstractAnycastRp                       string       `json:"abstract_anycast_rp,omitempty"`
	AbstractLoopbackInterface               string       `json:"abstract_loopback_interface,omitempty"`
	AbstractIsis                            string       `json:"abstract_isis,omitempty"`
	AbstractOspf                            string       `json:"abstract_ospf,omitempty"`
	AbstractVpcDomain                       string       `json:"abstract_vpc_domain,omitempty"`
	AbstractVlanInterface                   string       `json:"abstract_vlan_interface,omitempty"`
	AbstractIsisInterface                   string       `json:"abstract_isis_interface,omitempty"`
	AbstractOspfInterface                   string       `json:"abstract_ospf_interface,omitempty"`
	AbstractPimInterface                    string       `json:"abstract_pim_interface,omitempty"`
	AbstractRouteMap                        string       `json:"abstract_route_map,omitempty"`
	AbstractBgp                             string       `json:"abstract_bgp,omitempty"`
	AbstractBgpRr                           string       `json:"abstract_bgp_rr,omitempty"`
	AbstractBgpNeighbor                     string       `json:"abstract_bgp_neighbor,omitempty"`
	AbstractExtraConfigLeaf                 string       `json:"abstract_extra_config_leaf,omitempty"`
	AbstractExtraConfigSpine                string       `json:"abstract_extra_config_spine,omitempty"`
	AbstractExtraConfigTor                  string       `json:"abstract_extra_config_tor,omitempty"`
	AbstractExtraConfigBootstrap            string       `json:"abstract_extra_config_bootstrap,omitempty"`
	TempAnycastGateway                      string       `json:"temp_anycast_gateway,omitempty"`
	TempVpcDomainMgmt                       string       `json:"temp_vpc_domain_mgmt,omitempty"`
	TempVpcPeerLink                         string       `json:"temp_vpc_peer_link,omitempty"`
	AbstractRoutedHost                      string       `json:"abstract_routed_host,omitempty"`
	UpgradeFromVersion                      string       `json:"UPGRADE_FROM_VERSION,omitempty"`
	TopdownConfigRmTracking                 string       `json:"TOPDOWN_CONFIG_RM_TRACKING,omitempty"`
	SiteIdPolicyId                          *Int64Custom `json:"SITE_ID_POLICY_ID,omitempty"`
	FabricVpcDomainIdPrev                   *Int64Custom `json:"FABRIC_VPC_DOMAIN_ID_PREV,omitempty"`
	LinkStateRoutingTagPrev                 string       `json:"LINK_STATE_ROUTING_TAG_PREV,omitempty"`
	BfdEnablePrev                           string       `json:"BFD_ENABLE_PREV,omitempty"`
	EnableSgtPrev                           string       `json:"ENABLE_SGT_PREV,omitempty"`
	SgtPreprovisionPrev                     string       `json:"SGT_PREPROVISION_PREV,omitempty"`
	SgtPreprovRecalcStatus                  string       `json:"SGT_PREPROV_RECALC_STATUS,omitempty"`
	SgtRecalcStatus                         string       `json:"SGT_RECALC_STATUS,omitempty"`
	SgtOperStatus                           string       `json:"SGT_OPER_STATUS,omitempty"`
	EnableMacsecPrev                        string       `json:"ENABLE_MACSEC_PREV,omitempty"`
	EnableDciMacsecPrev                     string       `json:"ENABLE_DCI_MACSEC_PREV,omitempty"`
	DciMacsecFallbackKeyString              string       `json:"DCI_MACSEC_FALLBACK_KEY_STRING,omitempty"`
	DciMacsecFallbackAlgorithm              string       `json:"DCI_MACSEC_FALLBACK_ALGORITHM,omitempty"`
	DciMacsecAlgorithm                      string       `json:"DCI_MACSEC_ALGORITHM,omitempty"`
	DciMacsecKeyString                      string       `json:"DCI_MACSEC_KEY_STRING,omitempty"`
	DciMacsecCipherSuite                    string       `json:"DCI_MACSEC_CIPHER_SUITE,omitempty"`
	QkdProfileNamePrev                      string       `json:"QKD_PROFILE_NAME_PREV,omitempty"`
	FabricMtuPrev                           *Int64Custom `json:"FABRIC_MTU_PREV,omitempty"`
	L2HostIntfMtuPrev                       *Int64Custom `json:"L2_HOST_INTF_MTU_PREV,omitempty"`
	MplsIsisAreaNumPrev                     string       `json:"MPLS_ISIS_AREA_NUM_PREV,omitempty"`
	IsisAreaNumPrev                         string       `json:"ISIS_AREA_NUM_PREV,omitempty"`
	EnableAiMlQosPolicyFlap                 string       `json:"ENABLE_AI_ML_QOS_POLICY_FLAP,omitempty"`
	PfcWatchIntPrev                         *Int64Custom `json:"PFC_WATCH_INT_PREV,omitempty"`
	InbandMgmtPrev                          string       `json:"INBAND_MGMT_PREV,omitempty"`
	BootstrapEnablePrev                     string       `json:"BOOTSTRAP_ENABLE_PREV,omitempty"`
	EnableNetflowPrev                       string       `json:"ENABLE_NETFLOW_PREV,omitempty"`
	AllowNxcPrev                            string       `json:"ALLOW_NXC_PREV,omitempty"`
	EnableNbmPassivePrev                    string       `json:"ENABLE_NBM_PASSIVE_PREV,omitempty"`
	FabricTechnology                        string       `json:"FABRIC_TECHNOLOGY,omitempty"`
	InterfaceEthernetDefaultPolicy          string       `json:"INTERFACE_ETHERNET_DEFAULT_POLICY,omitempty"`
	InterfaceLoopbackDefaultPolicy          string       `json:"INTERFACE_LOOPBACK_DEFAULT_POLICY,omitempty"`
	InterfacePortChannelDefaultPolicy       string       `json:"INTERFACE_PORT_CHANNEL_DEFAULT_POLICY,omitempty"`
	InterfaceVlanDefaultPolicy              string       `json:"INTERFACE_VLAN_DEFAULT_POLICY,omitempty"`
	RpIpRangeInternal                       string       `json:"RP_IP_RANGE_INTERNAL,omitempty"`
	InbandEnablePrev                        string       `json:"INBAND_ENABLE_PREV,omitempty"`
	EnableAsm                               string       `json:"ENABLE_ASM,omitempty"`
	DomainNameInternal                      string       `json:"DOMAIN_NAME_INTERNAL,omitempty"`
	PnpEnableInternal                       string       `json:"PNP_ENABLE_INTERNAL,omitempty"`
	BgwRoutingTag                           *Int64Custom `json:"BGW_ROUTING_TAG,omitempty"`
	DcnmId                                  string       `json:"DCNM_ID,omitempty"`
	EnableTrmTrmv6                          string       `json:"ENABLE_TRM_TRMv6,omitempty"`
	EnableTrmTrmv6Prev                      string       `json:"ENABLE_TRM_TRMv6_PREV,omitempty"`
	Loopback100Ipv6Range                    string       `json:"LOOPBACK100_IPV6_RANGE,omitempty"`
	BgwRoutingTagPrev                       string       `json:"BGW_ROUTING_TAG_PREV,omitempty"`
	MsIfcBgpAuthKeyTypePrev                 *Int64Custom `json:"MS_IFC_BGP_AUTH_KEY_TYPE_PREV,omitempty"`
	MsIfcBgpPasswordEnablePrev              string       `json:"MS_IFC_BGP_PASSWORD_ENABLE_PREV,omitempty"`
	MsIfcBgpPasswordPrev                    string       `json:"MS_IFC_BGP_PASSWORD_PREV,omitempty"`
	ParentOnemanageFabric                   string       `json:"PARENT_ONEMANAGE_FABRIC,omitempty"`
	SgtIdRangePrev                          string       `json:"SGT_ID_RANGE_PREV,omitempty"`
	SgtNamePrefixPrev                       string       `json:"SGT_NAME_PREFIX_PREV,omitempty"`
	V6DciSubnetRange                        string       `json:"V6_DCI_SUBNET_RANGE,omitempty"`
	V6DciSubnetTargetMask                   *Int64Custom `json:"V6_DCI_SUBNET_TARGET_MASK,omitempty"`
	VxlanUnderlayIsV6                       string       `json:"VXLAN_UNDERLAY_IS_V6,omitempty"`
}
