// Copyright (c) 2025 Cisco Systems, Inc. and its affiliates
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated;  DO NOT EDIT.

package resource_fabric_common

import (
	. "terraform-provider-ndfc/internal/provider/types"
)

type NDFCFabricCommonModel struct {
	FabricName                              string       `json:"FABRIC_NAME,omitempty"`
	AaaRemoteIpEnabled                      string       `json:"AAA_REMOTE_IP_ENABLED,omitempty"`
	AaaServerConf                           string       `json:"AAA_SERVER_CONF,omitempty"`
	AsmGroupRanges                          string       `json:"ASM_GROUP_RANGES,omitempty"`
	BootstrapConf                           string       `json:"BOOTSTRAP_CONF,omitempty"`
	BootstrapEnable                         string       `json:"BOOTSTRAP_ENABLE,omitempty"`
	BootstrapMultisubnet                    string       `json:"BOOTSTRAP_MULTISUBNET,omitempty"`
	CdpEnable                               string       `json:"CDP_ENABLE,omitempty"`
	DhcpEnable                              string       `json:"DHCP_ENABLE,omitempty"`
	DhcpEnd                                 string       `json:"DHCP_END,omitempty"`
	DhcpIpv6Enable                          string       `json:"DHCP_IPV6_ENABLE,omitempty"`
	DhcpStart                               string       `json:"DHCP_START,omitempty"`
	DnsServerIpList                         string       `json:"DNS_SERVER_IP_LIST,omitempty"`
	DnsServerVrf                            string       `json:"DNS_SERVER_VRF,omitempty"`
	EnableAaa                               string       `json:"ENABLE_AAA,omitempty"`
	EnableAsm                               string       `json:"ENABLE_ASM,omitempty"`
	EnableNbmPassive                        string       `json:"ENABLE_NBM_PASSIVE,omitempty"`
	ExtraConfIntraLinks                     string       `json:"EXTRA_CONF_INTRA_LINKS,omitempty"`
	ExtraConfLeaf                           string       `json:"EXTRA_CONF_LEAF,omitempty"`
	ExtraConfSpine                          string       `json:"EXTRA_CONF_SPINE,omitempty"`
	FabricInterfaceType                     string       `json:"FABRIC_INTERFACE_TYPE,omitempty"`
	FabricMtu                               *Int64Custom `json:"FABRIC_MTU,omitempty"`
	FeaturePtp                              string       `json:"FEATURE_PTP,omitempty"`
	IsisAuthEnable                          string       `json:"ISIS_AUTH_ENABLE,omitempty"`
	IsisAuthKey                             string       `json:"ISIS_AUTH_KEY,omitempty"`
	IsisAuthKeychainKeyId                   *Int64Custom `json:"ISIS_AUTH_KEYCHAIN_KEY_ID,omitempty"`
	IsisAuthKeychainName                    string       `json:"ISIS_AUTH_KEYCHAIN_NAME,omitempty"`
	IsisLevel                               string       `json:"ISIS_LEVEL,omitempty"`
	IsisP2pEnable                           string       `json:"ISIS_P2P_ENABLE,omitempty"`
	L2HostIntfMtu                           *Int64Custom `json:"L2_HOST_INTF_MTU,omitempty"`
	LinkStateRouting                        string       `json:"LINK_STATE_ROUTING,omitempty"`
	LinkStateRoutingTag                     string       `json:"LINK_STATE_ROUTING_TAG,omitempty"`
	Loopback0IpRange                        string       `json:"LOOPBACK0_IP_RANGE,omitempty"`
	MgmtGw                                  string       `json:"MGMT_GW,omitempty"`
	MgmtPrefix                              *Int64Custom `json:"MGMT_PREFIX,omitempty"`
	NtpServerIpList                         string       `json:"NTP_SERVER_IP_LIST,omitempty"`
	NtpServerVrf                            string       `json:"NTP_SERVER_VRF,omitempty"`
	NxapiVrf                                string       `json:"NXAPI_VRF,omitempty"`
	OspfAreaId                              string       `json:"OSPF_AREA_ID,omitempty"`
	OspfAuthEnable                          string       `json:"OSPF_AUTH_ENABLE,omitempty"`
	OspfAuthKey                             string       `json:"OSPF_AUTH_KEY,omitempty"`
	OspfAuthKeyId                           *Int64Custom `json:"OSPF_AUTH_KEY_ID,omitempty"`
	PimHelloAuthEnable                      string       `json:"PIM_HELLO_AUTH_ENABLE,omitempty"`
	PimHelloAuthKey                         string       `json:"PIM_HELLO_AUTH_KEY,omitempty"`
	PmEnable                                string       `json:"PM_ENABLE,omitempty"`
	PowerRedundancyMode                     string       `json:"POWER_REDUNDANCY_MODE,omitempty"`
	PtpDomainId                             *Int64Custom `json:"PTP_DOMAIN_ID,omitempty"`
	PtpLbId                                 *Int64Custom `json:"PTP_LB_ID,omitempty"`
	PtpProfile                              string       `json:"PTP_PROFILE,omitempty"`
	RoutingLbId                             *Int64Custom `json:"ROUTING_LB_ID,omitempty"`
	RpIpRange                               string       `json:"RP_IP_RANGE,omitempty"`
	RpLbId                                  *Int64Custom `json:"RP_LB_ID,omitempty"`
	SnmpServerHostTrap                      string       `json:"SNMP_SERVER_HOST_TRAP,omitempty"`
	StaticUnderlayIpAlloc                   string       `json:"STATIC_UNDERLAY_IP_ALLOC,omitempty"`
	SubnetRange                             string       `json:"SUBNET_RANGE,omitempty"`
	SubnetTargetMask                        *Int64Custom `json:"SUBNET_TARGET_MASK,omitempty"`
	SyslogServerIpList                      string       `json:"SYSLOG_SERVER_IP_LIST,omitempty"`
	SyslogServerVrf                         string       `json:"SYSLOG_SERVER_VRF,omitempty"`
	SyslogSev                               string       `json:"SYSLOG_SEV,omitempty"`
	BgpAs                                   string       `json:"BGP_AS,omitempty"`
	BootstrapConfXe                         string       `json:"BOOTSTRAP_CONF_XE,omitempty"`
	DomainName                              string       `json:"DOMAIN_NAME,omitempty"`
	EnableNetflow                           string       `json:"ENABLE_NETFLOW,omitempty"`
	EnableNxapi                             string       `json:"ENABLE_NXAPI,omitempty"`
	EnableNxapiHttp                         string       `json:"ENABLE_NXAPI_HTTP,omitempty"`
	EnableRtIntfStats                       string       `json:"ENABLE_RT_INTF_STATS,omitempty"`
	FabricFreeform                          string       `json:"FABRIC_FREEFORM,omitempty"`
	InbandEnable                            string       `json:"INBAND_ENABLE,omitempty"`
	InbandMgmt                              string       `json:"INBAND_MGMT,omitempty"`
	IntfStatLoadInterval                    *Int64Custom `json:"INTF_STAT_LOAD_INTERVAL,omitempty"`
	IsReadOnly                              string       `json:"IS_READ_ONLY,omitempty"`
	MgmtV6prefix                            *Int64Custom `json:"MGMT_V6PREFIX,omitempty"`
	MplsHandoff                             string       `json:"MPLS_HANDOFF,omitempty"`
	MplsLbId                                *Int64Custom `json:"MPLS_LB_ID,omitempty"`
	MplsLoopbackIpRange                     string       `json:"MPLS_LOOPBACK_IP_RANGE,omitempty"`
	NetflowExporterList                     string       `json:"NETFLOW_EXPORTER_LIST,omitempty"`
	NetflowMonitorList                      string       `json:"NETFLOW_MONITOR_LIST,omitempty"`
	NetflowRecordList                       string       `json:"NETFLOW_RECORD_LIST,omitempty"`
	NetflowSamplerList                      string       `json:"NETFLOW_SAMPLER_LIST,omitempty"`
	NxapiHttpsPort                          *Int64Custom `json:"NXAPI_HTTPS_PORT,omitempty"`
	NxapiHttpPort                           *Int64Custom `json:"NXAPI_HTTP_PORT,omitempty"`
	PnpEnable                               string       `json:"PNP_ENABLE,omitempty"`
	SubinterfaceRange                       string       `json:"SUBINTERFACE_RANGE,omitempty"`
	EnableRealtimeBackup                    string       `json:"enableRealTimeBackup,omitempty"`
	EnableScheduledBackup                   string       `json:"enableScheduledBackup,omitempty"`
	ScheduledTime                           string       `json:"scheduledTime,omitempty"`
	AdvertisePipBgp                         string       `json:"ADVERTISE_PIP_BGP,omitempty"`
	AdvertisePipOnBorder                    string       `json:"ADVERTISE_PIP_ON_BORDER,omitempty"`
	AnycastBgwAdvertisePip                  string       `json:"ANYCAST_BGW_ADVERTISE_PIP,omitempty"`
	AnycastGwMac                            string       `json:"ANYCAST_GW_MAC,omitempty"`
	AnycastLbId                             *Int64Custom `json:"ANYCAST_LB_ID,omitempty"`
	AnycastRpIpRange                        string       `json:"ANYCAST_RP_IP_RANGE,omitempty"`
	AutoSymmetricDefaultVrf                 string       `json:"AUTO_SYMMETRIC_DEFAULT_VRF,omitempty"`
	AutoSymmetricVrfLite                    string       `json:"AUTO_SYMMETRIC_VRF_LITE,omitempty"`
	AutoUniqueVrfLiteIpPrefix               string       `json:"AUTO_UNIQUE_VRF_LITE_IP_PREFIX,omitempty"`
	AutoVrfliteIfcDefaultVrf                string       `json:"AUTO_VRFLITE_IFC_DEFAULT_VRF,omitempty"`
	Banner                                  string       `json:"BANNER,omitempty"`
	BfdAuthEnable                           string       `json:"BFD_AUTH_ENABLE,omitempty"`
	BfdAuthKey                              string       `json:"BFD_AUTH_KEY,omitempty"`
	BfdAuthKeyId                            *Int64Custom `json:"BFD_AUTH_KEY_ID,omitempty"`
	BfdEnable                               string       `json:"BFD_ENABLE,omitempty"`
	BfdIbgpEnable                           string       `json:"BFD_IBGP_ENABLE,omitempty"`
	BfdIsisEnable                           string       `json:"BFD_ISIS_ENABLE,omitempty"`
	BfdOspfEnable                           string       `json:"BFD_OSPF_ENABLE,omitempty"`
	BfdPimEnable                            string       `json:"BFD_PIM_ENABLE,omitempty"`
	BgpAuthEnable                           string       `json:"BGP_AUTH_ENABLE,omitempty"`
	BgpAuthKey                              string       `json:"BGP_AUTH_KEY,omitempty"`
	BgpAuthKeyType                          *Int64Custom `json:"BGP_AUTH_KEY_TYPE,omitempty"`
	BgpLbId                                 *Int64Custom `json:"BGP_LB_ID,omitempty"`
	BrownfieldNetworkNameFormat             string       `json:"BROWNFIELD_NETWORK_NAME_FORMAT,omitempty"`
	BrownfieldSkipOverlayNetworkAttachments string       `json:"BROWNFIELD_SKIP_OVERLAY_NETWORK_ATTACHMENTS,omitempty"`
	CoppPolicy                              string       `json:"COPP_POLICY,omitempty"`
	DciSubnetRange                          string       `json:"DCI_SUBNET_RANGE,omitempty"`
	DciSubnetTargetMask                     *Int64Custom `json:"DCI_SUBNET_TARGET_MASK,omitempty"`
	DefaultQueuingPolicyCloudscale          string       `json:"DEAFULT_QUEUING_POLICY_CLOUDSCALE,omitempty"`
	DefaultQueuingPolicyOther               string       `json:"DEAFULT_QUEUING_POLICY_OTHER,omitempty"`
	DefaultQueuingPolicyRSeries             string       `json:"DEAFULT_QUEUING_POLICY_R_SERIES,omitempty"`
	DefaultVrfRedisBgpRmap                  string       `json:"DEFAULT_VRF_REDIS_BGP_RMAP,omitempty"`
	EnableDefaultQueuingPolicy              string       `json:"ENABLE_DEFAULT_QUEUING_POLICY,omitempty"`
	EnableFabricVpcDomainId                 string       `json:"ENABLE_FABRIC_VPC_DOMAIN_ID,omitempty"`
	EnableMacsec                            string       `json:"ENABLE_MACSEC,omitempty"`
	EnableNgoam                             string       `json:"ENABLE_NGOAM,omitempty"`
	EnablePbr                               string       `json:"ENABLE_PBR,omitempty"`
	EnablePvlan                             string       `json:"ENABLE_PVLAN,omitempty"`
	EnableTenantDhcp                        string       `json:"ENABLE_TENANT_DHCP,omitempty"`
	EnableTrm                               string       `json:"ENABLE_TRM,omitempty"`
	EnableVpcPeerLinkNativeVlan             string       `json:"ENABLE_VPC_PEER_LINK_NATIVE_VLAN,omitempty"`
	ExtraConfTor                            string       `json:"EXTRA_CONF_TOR,omitempty"`
	FabricVpcDomainId                       *Int64Custom `json:"FABRIC_VPC_DOMAIN_ID,omitempty"`
	FabricVpcQos                            string       `json:"FABRIC_VPC_QOS,omitempty"`
	FabricVpcQosPolicyName                  string       `json:"FABRIC_VPC_QOS_POLICY_NAME,omitempty"`
	GrfieldDebugFlag                        string       `json:"GRFIELD_DEBUG_FLAG,omitempty"`
	HdTime                                  *Int64Custom `json:"HD_TIME,omitempty"`
	HostIntfAdminState                      string       `json:"HOST_INTF_ADMIN_STATE,omitempty"`
	IbgpPeerTemplate                        string       `json:"IBGP_PEER_TEMPLATE,omitempty"`
	IbgpPeerTemplateLeaf                    string       `json:"IBGP_PEER_TEMPLATE_LEAF,omitempty"`
	InbandDhcpServers                       string       `json:"INBAND_DHCP_SERVERS,omitempty"`
	IsisOverloadElapseTime                  *Int64Custom `json:"ISIS_OVERLOAD_ELAPSE_TIME,omitempty"`
	IsisOverloadEnable                      string       `json:"ISIS_OVERLOAD_ENABLE,omitempty"`
	L2SegmentIdRange                        string       `json:"L2_SEGMENT_ID_RANGE,omitempty"`
	L3vniMcastGroup                         string       `json:"L3VNI_MCAST_GROUP,omitempty"`
	L3PartitionIdRange                      string       `json:"L3_PARTITION_ID_RANGE,omitempty"`
	Loopback0Ipv6Range                      string       `json:"LOOPBACK0_IPV6_RANGE,omitempty"`
	Loopback1Ipv6Range                      string       `json:"LOOPBACK1_IPV6_RANGE,omitempty"`
	Loopback1IpRange                        string       `json:"LOOPBACK1_IP_RANGE,omitempty"`
	MacsecAlgorithm                         string       `json:"MACSEC_ALGORITHM,omitempty"`
	MacsecCipherSuite                       string       `json:"MACSEC_CIPHER_SUITE,omitempty"`
	MacsecFallbackAlgorithm                 string       `json:"MACSEC_FALLBACK_ALGORITHM,omitempty"`
	MacsecFallbackKeyString                 string       `json:"MACSEC_FALLBACK_KEY_STRING,omitempty"`
	MacsecKeyString                         string       `json:"MACSEC_KEY_STRING,omitempty"`
	MacsecReportTimer                       *Int64Custom `json:"MACSEC_REPORT_TIMER,omitempty"`
	MstInstanceRange                        string       `json:"MST_INSTANCE_RANGE,omitempty"`
	MulticastGroupSubnet                    string       `json:"MULTICAST_GROUP_SUBNET,omitempty"`
	NetworkVlanRange                        string       `json:"NETWORK_VLAN_RANGE,omitempty"`
	NveLbId                                 *Int64Custom `json:"NVE_LB_ID,omitempty"`
	ObjectTrackingNumberRange               string       `json:"OBJECT_TRACKING_NUMBER_RANGE,omitempty"`
	OverlayMode                             string       `json:"OVERLAY_MODE,omitempty"`
	PerVrfLoopbackAutoProvision             string       `json:"PER_VRF_LOOPBACK_AUTO_PROVISION,omitempty"`
	PerVrfLoopbackIpRange                   string       `json:"PER_VRF_LOOPBACK_IP_RANGE,omitempty"`
	PhantomRpLbId1                          *Int64Custom `json:"PHANTOM_RP_LB_ID1,omitempty"`
	PhantomRpLbId2                          *Int64Custom `json:"PHANTOM_RP_LB_ID2,omitempty"`
	PhantomRpLbId3                          *Int64Custom `json:"PHANTOM_RP_LB_ID3,omitempty"`
	PhantomRpLbId4                          *Int64Custom `json:"PHANTOM_RP_LB_ID4,omitempty"`
	ReplicationMode                         string       `json:"REPLICATION_MODE,omitempty"`
	RouterIdRange                           string       `json:"ROUTER_ID_RANGE,omitempty"`
	RouteMapSequenceNumberRange             string       `json:"ROUTE_MAP_SEQUENCE_NUMBER_RANGE,omitempty"`
	RpCount                                 *Int64Custom `json:"RP_COUNT,omitempty"`
	RpMode                                  string       `json:"RP_MODE,omitempty"`
	RrCount                                 *Int64Custom `json:"RR_COUNT,omitempty"`
	SeedSwitchCoreInterfaces                string       `json:"SEED_SWITCH_CORE_INTERFACES,omitempty"`
	ServiceNetworkVlanRange                 string       `json:"SERVICE_NETWORK_VLAN_RANGE,omitempty"`
	SiteId                                  string       `json:"SITE_ID,omitempty"`
	SlaIdRange                              string       `json:"SLA_ID_RANGE,omitempty"`
	SpineSwitchCoreInterfaces               string       `json:"SPINE_SWITCH_CORE_INTERFACES,omitempty"`
	StpBridgePriority                       *Int64Custom `json:"STP_BRIDGE_PRIORITY,omitempty"`
	StpRootOption                           string       `json:"STP_ROOT_OPTION,omitempty"`
	StpVlanRange                            string       `json:"STP_VLAN_RANGE,omitempty"`
	StrictCcMode                            string       `json:"STRICT_CC_MODE,omitempty"`
	TcamAllocation                          string       `json:"TCAM_ALLOCATION,omitempty"`
	UnderlayIsV6                            string       `json:"UNDERLAY_IS_V6,omitempty"`
	UnnumBootstrapLbId                      *Int64Custom `json:"UNNUM_BOOTSTRAP_LB_ID,omitempty"`
	UnnumDhcpEnd                            string       `json:"UNNUM_DHCP_END,omitempty"`
	UnnumDhcpStart                          string       `json:"UNNUM_DHCP_START,omitempty"`
	UseLinkLocal                            string       `json:"USE_LINK_LOCAL,omitempty"`
	V6SubnetRange                           string       `json:"V6_SUBNET_RANGE,omitempty"`
	V6SubnetTargetMask                      *Int64Custom `json:"V6_SUBNET_TARGET_MASK,omitempty"`
	VpcAutoRecoveryTime                     *Int64Custom `json:"VPC_AUTO_RECOVERY_TIME,omitempty"`
	VpcDelayRestore                         *Int64Custom `json:"VPC_DELAY_RESTORE,omitempty"`
	VpcDomainIdRange                        string       `json:"VPC_DOMAIN_ID_RANGE,omitempty"`
	VpcEnableIpv6NdSync                     string       `json:"VPC_ENABLE_IPv6_ND_SYNC,omitempty"`
	VpcPeerKeepAliveOption                  string       `json:"VPC_PEER_KEEP_ALIVE_OPTION,omitempty"`
	VpcPeerLinkPo                           *Int64Custom `json:"VPC_PEER_LINK_PO,omitempty"`
	VpcPeerLinkVlan                         *Int64Custom `json:"VPC_PEER_LINK_VLAN,omitempty"`
	VrfLiteAutoconfig                       string       `json:"VRF_LITE_AUTOCONFIG,omitempty"`
	VrfVlanRange                            string       `json:"VRF_VLAN_RANGE,omitempty"`
	DefaultNetwork                          string       `json:"default_network,omitempty"`
	DefaultPvlanSecNetwork                  string       `json:"default_pvlan_sec_network,omitempty"`
	DefaultVrf                              string       `json:"default_vrf,omitempty"`
	NetworkExtensionTemplate                string       `json:"network_extension_template,omitempty"`
	VrfExtensionTemplate                    string       `json:"vrf_extension_template,omitempty"`
	BgpRpAsn                                string       `json:"BGP_RP_ASN,omitempty"`
	BgwRoutingTag                           *Int64Custom `json:"BGW_ROUTING_TAG,omitempty"`
	BorderGwyConnections                    string       `json:"BORDER_GWY_CONNECTIONS,omitempty"`
	CloudsecAlgorithm                       string       `json:"CLOUDSEC_ALGORITHM,omitempty"`
	CloudsecAutoconfig                      string       `json:"CLOUDSEC_AUTOCONFIG,omitempty"`
	CloudsecEnforcement                     string       `json:"CLOUDSEC_ENFORCEMENT,omitempty"`
	CloudsecKeyString                       string       `json:"CLOUDSEC_KEY_STRING,omitempty"`
	CloudsecReportTimer                     *Int64Custom `json:"CLOUDSEC_REPORT_TIMER,omitempty"`
	DelayRestore                            *Int64Custom `json:"DELAY_RESTORE,omitempty"`
	EnableBgpBfd                            string       `json:"ENABLE_BGP_BFD,omitempty"`
	EnableBgpLogNeighborChange              string       `json:"ENABLE_BGP_LOG_NEIGHBOR_CHANGE,omitempty"`
	EnableBgpSendComm                       string       `json:"ENABLE_BGP_SEND_COMM,omitempty"`
	EnableRsRedistDirect                    string       `json:"ENABLE_RS_REDIST_DIRECT,omitempty"`
	Loopback100IpRange                      string       `json:"LOOPBACK100_IP_RANGE,omitempty"`
	MsIfcBgpAuthKeyType                     *Int64Custom `json:"MS_IFC_BGP_AUTH_KEY_TYPE,omitempty"`
	MsIfcBgpPassword                        string       `json:"MS_IFC_BGP_PASSWORD,omitempty"`
	MsIfcBgpPasswordEnable                  string       `json:"MS_IFC_BGP_PASSWORD_ENABLE,omitempty"`
	MsLoopbackId                            *Int64Custom `json:"MS_LOOPBACK_ID,omitempty"`
	MsUnderlayAutoconfig                    string       `json:"MS_UNDERLAY_AUTOCONFIG,omitempty"`
	RpServerIp                              string       `json:"RP_SERVER_IP,omitempty"`
	RsRoutingTag                            *Int64Custom `json:"RS_ROUTING_TAG,omitempty"`
	TorAutoDeploy                           string       `json:"TOR_AUTO_DEPLOY,omitempty"`
	Deploy                                  bool         `json:"-"`
	DeploymentStatus                        string       `json:"-"`
}
