// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_fabric_vxlan_msd

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FabricVxlanMsdResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"anycast_gw_mac": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Shared MAC address for all leaves",
				MarkdownDescription: "Shared MAC address for all leaves",
				Default:             stringdefault.StaticString("2020.0000.00aa"),
			},
			"bgp_rp_asn": schema.StringAttribute{
				Optional:            true,
				Description:         "1-4294967295 | 1-65535.0-65535, e.g. 65000, 65001",
				MarkdownDescription: "1-4294967295 | 1-65535.0-65535, e.g. 65000, 65001",
			},
			"bgw_routing_tag": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Routing tag associated with IP address of loopback and DCI interfaces",
				MarkdownDescription: "Routing tag associated with IP address of loopback and DCI interfaces",
				Default:             int64default.StaticInt64(54321),
			},
			"border_gwy_connections": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Manual, Auto Overlay EVPN Peering to Route Servers, Auto Overlay EVPN Direct Peering to Border Gateways",
				MarkdownDescription: "Manual, Auto Overlay EVPN Peering to Route Servers, Auto Overlay EVPN Direct Peering to Border Gateways",
				Validators: []validator.String{
					stringvalidator.OneOf("Manual", "Centralized_To_Route_Server", "Direct_To_BGWS"),
				},
				Default: stringdefault.StaticString("Manual"),
			},
			"cloudsec_algorithm": schema.StringAttribute{
				Optional:            true,
				Description:         "AES_128_CMAC or AES_256_CMAC",
				MarkdownDescription: "AES_128_CMAC or AES_256_CMAC",
			},
			"cloudsec_autoconfig": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Auto Config CloudSec on Border Gateways",
				MarkdownDescription: "Auto Config CloudSec on Border Gateways",
				Default:             booldefault.StaticBool(false),
			},
			"cloudsec_enforcement": schema.StringAttribute{
				Optional:            true,
				Description:         "If set to strict, data across site must be encrypted.",
				MarkdownDescription: "If set to strict, data across site must be encrypted.",
			},
			"cloudsec_key_string": schema.StringAttribute{
				Optional:            true,
				Description:         "Cisco Type 7 Encrypted Octet String",
				MarkdownDescription: "Cisco Type 7 Encrypted Octet String",
			},
			"cloudsec_report_timer": schema.Int64Attribute{
				Optional:            true,
				Description:         "CloudSec Operational Status periodic report timer in minutes",
				MarkdownDescription: "CloudSec Operational Status periodic report timer in minutes",
			},
			"dci_subnet_range": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Address range to assign P2P DCI Links",
				MarkdownDescription: "Address range to assign P2P DCI Links",
				Default:             stringdefault.StaticString("10.10.1.0/24"),
			},
			"dci_subnet_target_mask": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Target Mask for Subnet Range",
				MarkdownDescription: "Target Mask for Subnet Range",
				Default:             int64default.StaticInt64(30),
			},
			"default_network": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Default Overlay Network Template For Leafs",
				MarkdownDescription: "Default Overlay Network Template For Leafs",
				Validators: []validator.String{
					stringvalidator.OneOf("Default_Network_Universal", "Service_Network_Universal"),
				},
				Default: stringdefault.StaticString("Default_Network_Universal"),
			},
			"default_pvlan_sec_network": schema.StringAttribute{
				Optional:            true,
				Description:         "Default PVLAN Secondary Network Template",
				MarkdownDescription: "Default PVLAN Secondary Network Template",
			},
			"default_vrf": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Default Overlay VRF Template For Leafs",
				MarkdownDescription: "Default Overlay VRF Template For Leafs",
				Default:             stringdefault.StaticString("Default_VRF_Universal"),
			},
			"delay_restore": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Multi-Site underlay and overlay control plane convergence time in seconds",
				MarkdownDescription: "Multi-Site underlay and overlay control plane convergence time in seconds",
				Default:             int64default.StaticInt64(300),
			},
			"deploy": schema.BoolAttribute{
				Required:            true,
				Description:         "This flag does configuration save and deploy",
				MarkdownDescription: "This flag does configuration save and deploy",
			},
			"deployment_status": schema.StringAttribute{
				Computed:            true,
				Description:         "This fields shows the actual status of the deployment. It can be one of the following: Deployment pending Deployment successful",
				MarkdownDescription: "This fields shows the actual status of the deployment. It can be one of the following: Deployment pending Deployment successful",
			},
			"enable_bgp_bfd": schema.BoolAttribute{
				Optional:            true,
				Description:         "For auto-created Multi-Site Underlay IFCs",
				MarkdownDescription: "For auto-created Multi-Site Underlay IFCs",
			},
			"enable_bgp_log_neighbor_change": schema.BoolAttribute{
				Optional:            true,
				Description:         "For auto-created Multi-Site Underlay IFCs",
				MarkdownDescription: "For auto-created Multi-Site Underlay IFCs",
			},
			"enable_bgp_send_comm": schema.BoolAttribute{
				Optional:            true,
				Description:         "For auto-created Multi-Site Underlay IFCs",
				MarkdownDescription: "For auto-created Multi-Site Underlay IFCs",
			},
			"enable_pvlan": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enable PVLAN on MSD and its child fabrics",
				MarkdownDescription: "Enable PVLAN on MSD and its child fabrics",
				Default:             booldefault.StaticBool(false),
			},
			"enable_rs_redist_direct": schema.BoolAttribute{
				Optional:            true,
				Description:         "For auto-created Multi-Site overlay IFCs in Route Servers. Applicable only when Multi-Site Overlay IFC Deployment Method is Centralized_To_Route_Server.",
				MarkdownDescription: "For auto-created Multi-Site overlay IFCs in Route Servers. Applicable only when Multi-Site Overlay IFC Deployment Method is Centralized_To_Route_Server.",
			},
			"enable_scheduled_backup": schema.BoolAttribute{
				Optional:            true,
				Description:         "Backup at the specified time. Note: Fabric Backup/Restore functionality is being deprecated for MSD fabrics. Recommendation is to use NDFC Backup & Restore",
				MarkdownDescription: "Backup at the specified time. Note: Fabric Backup/Restore functionality is being deprecated for MSD fabrics. Recommendation is to use NDFC Backup & Restore",
			},
			"fabric_name": schema.StringAttribute{
				Required:            true,
				Description:         "Fabric name to be created, updated or deleted (Max Size 64).",
				MarkdownDescription: "Fabric name to be created, updated or deleted (Max Size 64).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Terraform unique Id for the fabric resource",
				MarkdownDescription: "Terraform unique Id for the fabric resource",
			},
			"l2_segment_id_range": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Overlay Network Identifier Range",
				MarkdownDescription: "Overlay Network Identifier Range",
				Default:             stringdefault.StaticString("30000-49000"),
			},
			"l3_partition_id_range": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Overlay VRF Identifier Range",
				MarkdownDescription: "Overlay VRF Identifier Range",
				Default:             stringdefault.StaticString("50000-59000"),
			},
			"loopback100_ip_range": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Typically Loopback100 IP Address Range",
				MarkdownDescription: "Typically Loopback100 IP Address Range",
				Default:             stringdefault.StaticString("10.10.0.0/24"),
			},
			"ms_ifc_bgp_auth_key_type": schema.Int64Attribute{
				Optional:            true,
				Description:         "BGP Key Encryption Type: 3 - 3DES, 7 - Cisco",
				MarkdownDescription: "BGP Key Encryption Type: 3 - 3DES, 7 - Cisco",
				Validators: []validator.Int64{
					int64validator.OneOf(3, 7),
				},
			},
			"ms_ifc_bgp_password": schema.StringAttribute{
				Optional:            true,
				Description:         "Encrypted eBGP Password Hex String",
				MarkdownDescription: "Encrypted eBGP Password Hex String",
			},
			"ms_ifc_bgp_password_enable": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "eBGP password for Multi-Site underlay/overlay IFCs",
				MarkdownDescription: "eBGP password for Multi-Site underlay/overlay IFCs",
				Default:             booldefault.StaticBool(false),
			},
			"ms_loopback_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "No description available",
				MarkdownDescription: "No description available",
				Default:             int64default.StaticInt64(100),
			},
			"ms_underlay_autoconfig": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "No description available",
				MarkdownDescription: "No description available",
				Default:             booldefault.StaticBool(false),
			},
			"network_extension_template": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Default Overlay Network Template For Borders",
				MarkdownDescription: "Default Overlay Network Template For Borders",
				Default:             stringdefault.StaticString("Default_Network_Extension_Universal"),
			},
			"rp_server_ip": schema.StringAttribute{
				Optional:            true,
				Description:         "Multi-Site Route-Server peer list (typically loopback IP address on Route-Server for Multi-Site EVPN peering with BGWs), e.g. 128.89.0.1, 128.89.0.2",
				MarkdownDescription: "Multi-Site Route-Server peer list (typically loopback IP address on Route-Server for Multi-Site EVPN peering with BGWs), e.g. 128.89.0.1, 128.89.0.2",
			},
			"rs_routing_tag": schema.Int64Attribute{
				Optional:            true,
				Description:         "Routing tag associated with Route Server IP for redistribute direct. This is the IP used in eBGP EVPN peering.",
				MarkdownDescription: "Routing tag associated with Route Server IP for redistribute direct. This is the IP used in eBGP EVPN peering.",
			},
			"scheduled_time": schema.StringAttribute{
				Optional:            true,
				Description:         "Time (UTC) in 24hr format. (00:00 to 23:59)",
				MarkdownDescription: "Time (UTC) in 24hr format. (00:00 to 23:59)",
			},
			"tor_auto_deploy": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enables Overlay VLANs on uplink between ToRs and Leafs",
				MarkdownDescription: "Enables Overlay VLANs on uplink between ToRs and Leafs",
				Default:             booldefault.StaticBool(false),
			},
			"vrf_extension_template": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Default Overlay VRF Template For Borders",
				MarkdownDescription: "Default Overlay VRF Template For Borders",
				Default:             stringdefault.StaticString("Default_VRF_Extension_Universal"),
			},
		},
		Description:         "Resource to configure and manage a VXLAN MSD Fabric",
		MarkdownDescription: "Resource to configure and manage a VXLAN MSD Fabric",
	}
}

type FabricVxlanMsdModel struct {
	AnycastGwMac               types.String `tfsdk:"anycast_gw_mac"`
	BgpRpAsn                   types.String `tfsdk:"bgp_rp_asn"`
	BgwRoutingTag              types.Int64  `tfsdk:"bgw_routing_tag"`
	BorderGwyConnections       types.String `tfsdk:"border_gwy_connections"`
	CloudsecAlgorithm          types.String `tfsdk:"cloudsec_algorithm"`
	CloudsecAutoconfig         types.Bool   `tfsdk:"cloudsec_autoconfig"`
	CloudsecEnforcement        types.String `tfsdk:"cloudsec_enforcement"`
	CloudsecKeyString          types.String `tfsdk:"cloudsec_key_string"`
	CloudsecReportTimer        types.Int64  `tfsdk:"cloudsec_report_timer"`
	DciSubnetRange             types.String `tfsdk:"dci_subnet_range"`
	DciSubnetTargetMask        types.Int64  `tfsdk:"dci_subnet_target_mask"`
	DefaultNetwork             types.String `tfsdk:"default_network"`
	DefaultPvlanSecNetwork     types.String `tfsdk:"default_pvlan_sec_network"`
	DefaultVrf                 types.String `tfsdk:"default_vrf"`
	DelayRestore               types.Int64  `tfsdk:"delay_restore"`
	Deploy                     types.Bool   `tfsdk:"deploy"`
	DeploymentStatus           types.String `tfsdk:"deployment_status"`
	EnableBgpBfd               types.Bool   `tfsdk:"enable_bgp_bfd"`
	EnableBgpLogNeighborChange types.Bool   `tfsdk:"enable_bgp_log_neighbor_change"`
	EnableBgpSendComm          types.Bool   `tfsdk:"enable_bgp_send_comm"`
	EnablePvlan                types.Bool   `tfsdk:"enable_pvlan"`
	EnableRsRedistDirect       types.Bool   `tfsdk:"enable_rs_redist_direct"`
	EnableScheduledBackup      types.Bool   `tfsdk:"enable_scheduled_backup"`
	FabricName                 types.String `tfsdk:"fabric_name"`
	Id                         types.String `tfsdk:"id"`
	L2SegmentIdRange           types.String `tfsdk:"l2_segment_id_range"`
	L3PartitionIdRange         types.String `tfsdk:"l3_partition_id_range"`
	Loopback100IpRange         types.String `tfsdk:"loopback100_ip_range"`
	MsIfcBgpAuthKeyType        types.Int64  `tfsdk:"ms_ifc_bgp_auth_key_type"`
	MsIfcBgpPassword           types.String `tfsdk:"ms_ifc_bgp_password"`
	MsIfcBgpPasswordEnable     types.Bool   `tfsdk:"ms_ifc_bgp_password_enable"`
	MsLoopbackId               types.Int64  `tfsdk:"ms_loopback_id"`
	MsUnderlayAutoconfig       types.Bool   `tfsdk:"ms_underlay_autoconfig"`
	NetworkExtensionTemplate   types.String `tfsdk:"network_extension_template"`
	RpServerIp                 types.String `tfsdk:"rp_server_ip"`
	RsRoutingTag               types.Int64  `tfsdk:"rs_routing_tag"`
	ScheduledTime              types.String `tfsdk:"scheduled_time"`
	TorAutoDeploy              types.Bool   `tfsdk:"tor_auto_deploy"`
	VrfExtensionTemplate       types.String `tfsdk:"vrf_extension_template"`
}
