package resource_interface_common

import "github.com/hashicorp/terraform-plugin-framework/diag"

type InterfaceModel interface {
	GetModelData() *NDFCInterfaceCommonModel
	SetModelData(*NDFCInterfaceCommonModel) diag.Diagnostics
	GetInterfaceType() string
	GetID() string
	SetID(string)
}

type InterfaceValue interface {
	SetValue(*NDFCInterfacesValue)
}

type NDFCInterfacesPayload struct {
	Policy     string                `json:"policy,omitempty"`
	Interfaces []NDFCInterfacesValue `json:"interfaces,omitempty"`
}

type NDFCInterfacesDeploy []NDFCInterfaceDeploy

type NDFCInterfaceDeploy struct {
	IfName       string `json:"ifName"`
	SerialNumber string `json:"serialNumber"`
}

/*
[
    {
        "allowAccessAdmin": true,
        "allowAccessAdminReason": null,
        "adminStatus": 1,
        "adminStatusStr": "up",
        "alias": "test 111111111 interface",
        "allowedVLANs": "",
        "channelId": -1,
        "channelIdStr": null,
        "channelIfIndex": -1,
        "complianceStatus": "Pending",
        "connectedTo": null,
        "connectedTo_2": null,
        "connectedToDbId": 0,
        "connectedToDbId_2": 0,
        "connectedToStr": "n9k-spine01:Ethernet1/1",
        "connectedToType": null,
        "connectedToType_2": null,
        "connToInterfaceIfName": null,
        "connToInterfaceIfName_2": null,
        "deleteReason": "Interface has overlay/vrf attached.",
        "description": null,
        "duplex": null,
        "editBlockReason": null,
        "entityId": "9FE076D8EJL~Ethernet1/1",
        "fabricName": "test_evpn_vxlan",
        "fid": 5,
        "ifIndex": 436207616,
        "ifName": "Ethernet1/1",
        "ifType": "INTERFACE_ETHERNET",
        "index": 64,
        "interfaceDbId": 51770,
        "ipAddress": null,
        "isFex": null,
        "isPhysical": "true",
        "isRbacAccessible": "true",
        "mgmtIpAddress": "192.168.20.10",
        "mode": "access",
        "mtu": 9216,
        "nativeVlanId": -1,
        "neighbours": [
            {
                "sysName": "n9k-spine01",
                "switchid": 51070,
                "type": "LAN",
                "ifName": "Ethernet1/1",
                "connectedToStr": "n9k-spine01:Ethernet1/1",
                "discovered": true
            }
        ],
        "operStatus": 1,
        "operStatusCause": "ok",
        "operStatusStr": "up",
        "overlayNetwork": [
            {
                "id": 172,
                "policyId": "172",
                "templateName": "Murali_nw_01",
                "entityName": "Ethernet1/1",
                "entityType": "INTERFACE",
                "status": "NA",
                "lastModified": null,
                "autoGenerated": true,
                "vrfProfile": false,
                "deleted": false
            }
        ],
        "overlayPoliciesStr": "Murali_nw_01",
        "overlayPolicyStr": null,
        "peerAAFexPortEntityId": null,
        "peerAAFexPortName": null,
        "platform": "N9K",
        "policyChangeSupported": false,
        "policyName": null,
        "policyNameStr": null,
        "portChannelMemberList": null,
        "portChannelMembers": null,
        "serialNo": "9FE076D8EJL",
        "sortIndex": 134,
        "speedStr": "1Gb",
        "speedValue": 1000000000,
        "switchDbId": 51030,
        "sysName": "n9k-leaf01",
        "underlayPolicies": [
            {
                "id": 52340,
                "policyId": "POLICY-52340",
                "templateName": "int_access_host",
                "entityName": "Ethernet1/1",
                "entityType": "INTERFACE",
                "status": "NA",
                "lastModified": 1711966348745,
                "source": "",
                "serialNumber": "9FE076D8EJL",
                "policyTag": null,
                "autoGenerated": true
            }
        ],
        "underlayPoliciesStr": "int_access_host",
        "vdcId": 0,
        "vdcName": null,
        "vpcEntityId": null,
        "vpcId": 0,
        "vrf": null,
        "vsanId": null,
        "portType": "access",
        "blockConfig": false,
        "underlayPolicySource": "",
        "underlayPolicyTag": "[interface_edit_policy]",
        "interfaceGroup": null,
        "hasDeletedOverlay": false,
        "aafexPort": false,
        "deletable": false,
        "discovered": true,
        "editAllowed": true,
        "externalFabric": false,
        "markDeleted": false,
        "groupAssocSupported": true
    }
]
*/

type NDFCInterfaceDetails struct {
	InterfaceName string `json:"ifName"`
	DeployStatus  string `json:"complianceStatus"`
}
