// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_configuration_deploy

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ConfigurationDeployResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"fabric_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the fabric",
				MarkdownDescription: "The name of the fabric",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The Terraform Unique Identifier for the Inventory Devices resource",
				MarkdownDescription: "The Terraform Unique Identifier for the Inventory Devices resource",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"serial_numbers": schema.SetAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "The serial numbers of the fabric to be deployed",
				MarkdownDescription: "The serial numbers of the fabric to be deployed",
			},
		},
	}
}

type ConfigurationDeployModel struct {
	FabricName    types.String `tfsdk:"fabric_name"`
	Id            types.String `tfsdk:"id"`
	SerialNumbers types.Set    `tfsdk:"serial_numbers"`
}
